'use client'

import { useState, useEffect } from 'react'
import { useAuth } from '@/context/AuthContext'
import { supabase } from '@/lib/supabaseClient'
import { useRouter } from 'next/navigation'
import { motion, AnimatePresence } from 'framer-motion'
import { hasPermission } from '@/lib/permissions'

interface User {
  UserID: number
  Email: string
  Name: string
  Role: 'user' | 'coach' | 'admin'
  CreatedAt: string
}

interface NewUser {
  email: string
  name: string
  role: 'user' | 'coach' | 'admin'
  password: string
}

export default function UserManagementPage() {
  const router = useRouter()
  const { currentUser } = useAuth()
  
  const [users, setUsers] = useState<User[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  
  // Modal states
  const [showAddModal, setShowAddModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [selectedUser, setSelectedUser] = useState<User | null>(null)
  
  // Form states
  const [newUser, setNewUser] = useState<NewUser>({
    email: '',
    name: '',
    role: 'user',
    password: '123456', // Default password (6 chars minimum)
  })

  // Check admin permission
  useEffect(() => {
    if (!currentUser || !hasPermission(currentUser.Role, 'view_users')) {
      router.push('/dashboard')
    }
  }, [currentUser, router])

  // Load users
  useEffect(() => {
    loadUsers()
  }, [])

  const loadUsers = async () => {
    try {
      setLoading(true)
      const { data, error } = await supabase
        .from('Users')
        .select('*')
        .order('Name')

      if (error) throw error
      setUsers(data || [])
    } catch (err: any) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const handleAddUser = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)

    try {
      // Step 1: Create auth user
      const { data: authData, error: authError } = await supabase.auth.signUp({
        email: newUser.email,
        password: newUser.password,
        options: {
          emailRedirectTo: undefined, // No email confirmation
        }
      })

      if (authError) throw authError

      // Step 2: Insert into Users table
      const { error: dbError } = await supabase
        .from('Users')
        .insert({
          Email: newUser.email,
          Name: newUser.name,
          Role: newUser.role,
          // UserID is auto-generated by sequence!
        })

      if (dbError) throw dbError

      // Success!
      alert(`משתמש ${newUser.name} נוצר בהצלחה!
        
אימייל: ${newUser.email}
סיסמה: ${newUser.password}
תפקיד: ${getRoleLabel(newUser.role)}

שתף את הפרטים עם המשתמש!`)

      setShowAddModal(false)
      setNewUser({ email: '', name: '', role: 'user', password: '123456' })
      loadUsers()
    } catch (err: any) {
      setError(err.message)
      alert(`שגיאה: ${err.message}`)
    }
  }

  const handleUpdateUser = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!selectedUser) return

    setError(null)

    try {
      const { error } = await supabase
        .from('Users')
        .update({
          Name: selectedUser.Name,
          Role: selectedUser.Role,
        })
        .eq('UserID', selectedUser.UserID)

      if (error) throw error

      alert('המשתמש עודכן בהצלחה!')
      setShowEditModal(false)
      setSelectedUser(null)
      loadUsers()
    } catch (err: any) {
      setError(err.message)
      alert(`שגיאה: ${err.message}`)
    }
  }

  const handleResetPassword = async (user: User) => {
    const confirmed = confirm(
      `האם לאפס את הסיסמה של ${user.Name}?\n\nסיסמה חדשה: 123456\n\nהמשתמש יצטרך להתחבר שוב.`
    )
    if (!confirmed) return

    try {
      // This requires admin privileges
      // For now, show instructions
      alert(`לאיפוס סיסמה:

1. לך ל-Supabase Dashboard
2. Authentication → Users
3. מצא את ${user.Email}
4. לחץ על ... → Reset Password
5. הגדר: 123456

(איפוס אוטומטי יתווסף בגרסה הבאה)`)
    } catch (err: any) {
      alert(`שגיאה: ${err.message}`)
    }
  }

  const getRoleLabel = (role: string) => {
    const labels = {
      admin: 'מנהל',
      coach: 'מאמן',
      user: 'משתמש',
    }
    return labels[role as keyof typeof labels] || role
  }

  const getRoleColor = (role: string) => {
    const colors = {
      admin: 'bg-red-100 text-red-700 border-red-300',
      coach: 'bg-blue-100 text-blue-700 border-blue-300',
      user: 'bg-green-100 text-green-700 border-green-300',
    }
    return colors[role as keyof typeof colors] || 'bg-gray-100 text-gray-700'
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 p-6" dir="rtl">
      {/* Header */}
      <div className="max-w-7xl mx-auto mb-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 flex items-center gap-2">
              👥 ניהול משתמשים
            </h1>
            <p className="text-gray-600 mt-1">
              {users.length} משתמשים במערכת
            </p>
          </div>
          
          <div className="flex gap-3">
            <button
              onClick={() => router.push('/dashboard')}
              className="px-4 py-2 border-2 border-gray-300 text-gray-700 rounded-lg hover:bg-gray-100 transition-all"
            >
              ← חזור
            </button>
            <button
              onClick={() => setShowAddModal(true)}
              className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-all flex items-center gap-2"
            >
              <span>➕</span>
              <span>משתמש חדש</span>
            </button>
          </div>
        </div>
      </div>

      {/* Error Alert */}
      {error && (
        <div className="max-w-7xl mx-auto mb-4 p-4 bg-red-50 border border-red-200 rounded-lg text-red-700">
          <strong>שגיאה:</strong> {error}
        </div>
      )}

      {/* Users Table */}
      <div className="max-w-7xl mx-auto bg-white rounded-xl shadow-lg overflow-hidden">
        <table className="w-full">
          <thead className="bg-gray-50 border-b-2 border-gray-200">
            <tr>
              <th className="px-6 py-4 text-right text-sm font-bold text-gray-700">
                שם
              </th>
              <th className="px-6 py-4 text-right text-sm font-bold text-gray-700">
                אימייל
              </th>
              <th className="px-6 py-4 text-right text-sm font-bold text-gray-700">
                תפקיד
              </th>
              <th className="px-6 py-4 text-right text-sm font-bold text-gray-700">
                תאריך הצטרפות
              </th>
              <th className="px-6 py-4 text-center text-sm font-bold text-gray-700">
                פעולות
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {users.map((user) => (
              <tr
                key={user.UserID}
                className="hover:bg-gray-50 transition-colors"
              >
                <td className="px-6 py-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-400 to-blue-600 flex items-center justify-center text-white font-bold">
                      {user.Name.charAt(0)}
                    </div>
                    <div>
                      <div className="font-semibold text-gray-900">
                        {user.Name}
                      </div>
                      {user.Email === currentUser?.Email && (
                        <span className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded">
                          אתה
                        </span>
                      )}
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4 text-gray-600 font-mono text-sm">
                  {user.Email}
                </td>
                <td className="px-6 py-4">
                  <span className={`inline-block px-3 py-1 rounded-full text-sm font-medium border ${getRoleColor(user.Role)}`}>
                    {getRoleLabel(user.Role)}
                  </span>
                </td>
                <td className="px-6 py-4 text-gray-600 text-sm">
                  {new Date(user.CreatedAt).toLocaleDateString('he-IL')}
                </td>
                <td className="px-6 py-4">
                  <div className="flex items-center justify-center gap-2">
                    <button
                      onClick={() => {
                        setSelectedUser(user)
                        setShowEditModal(true)
                      }}
                      className="px-3 py-1 bg-blue-50 text-blue-600 rounded hover:bg-blue-100 transition-all text-sm"
                    >
                      ✏️ עריכה
                    </button>
                    <button
                      onClick={() => handleResetPassword(user)}
                      className="px-3 py-1 bg-orange-50 text-orange-600 rounded hover:bg-orange-100 transition-all text-sm"
                    >
                      🔐 סיסמה
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {users.length === 0 && (
          <div className="text-center py-12 text-gray-500">
            אין משתמשים במערכת
          </div>
        )}
      </div>

      {/* Add User Modal */}
      <AnimatePresence>
        {showAddModal && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowAddModal(false)}
              className="fixed inset-0 bg-black bg-opacity-50 z-50"
            />
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                className="bg-white rounded-xl shadow-2xl w-full max-w-md"
              >
                <div className="bg-gradient-to-r from-blue-600 to-blue-700 px-6 py-4 rounded-t-xl">
                  <h2 className="text-2xl font-bold text-white">
                    ➕ משתמש חדש
                  </h2>
                </div>

                <form onSubmit={handleAddUser} className="p-6 space-y-4">
                  <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">
                      שם מלא
                    </label>
                    <input
                      type="text"
                      value={newUser.name}
                      onChange={(e) => setNewUser({ ...newUser, name: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                      placeholder="יוסי כהן"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">
                      אימייל
                    </label>
                    <input
                      type="email"
                      value={newUser.email}
                      onChange={(e) => setNewUser({ ...newUser, email: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                      placeholder="yossi@example.com"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">
                      סיסמה
                    </label>
                    <input
                      type="text"
                      value={newUser.password}
                      onChange={(e) => setNewUser({ ...newUser, password: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                      placeholder="123456"
                      required
                      minLength={6}
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      מינימום 6 תווים (ברירת מחדל: 123456)
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">
                      תפקיד
                    </label>
                    <select
                      value={newUser.role}
                      onChange={(e) => setNewUser({ ...newUser, role: e.target.value as any })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="user">👤 משתמש</option>
                      <option value="coach">👨‍🏫 מאמן</option>
                      <option value="admin">👑 מנהל</option>
                    </select>
                  </div>

                  <div className="flex gap-3 pt-4">
                    <button
                      type="button"
                      onClick={() => setShowAddModal(false)}
                      className="flex-1 px-4 py-3 border-2 border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
                    >
                      ביטול
                    </button>
                    <button
                      type="submit"
                      className="flex-1 px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                    >
                      ✅ צור משתמש
                    </button>
                  </div>
                </form>
              </motion.div>
            </div>
          </>
        )}
      </AnimatePresence>

      {/* Edit User Modal */}
      <AnimatePresence>
        {showEditModal && selectedUser && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowEditModal(false)}
              className="fixed inset-0 bg-black bg-opacity-50 z-50"
            />
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                className="bg-white rounded-xl shadow-2xl w-full max-w-md"
              >
                <div className="bg-gradient-to-r from-blue-600 to-blue-700 px-6 py-4 rounded-t-xl">
                  <h2 className="text-2xl font-bold text-white">
                    ✏️ עריכת משתמש
                  </h2>
                </div>

                <form onSubmit={handleUpdateUser} className="p-6 space-y-4">
                  <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">
                      שם מלא
                    </label>
                    <input
                      type="text"
                      value={selectedUser.Name}
                      onChange={(e) => setSelectedUser({ ...selectedUser, Name: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">
                      אימייל
                    </label>
                    <input
                      type="email"
                      value={selectedUser.Email}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg bg-gray-100 cursor-not-allowed"
                      disabled
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      לא ניתן לשנות אימייל (מחובר ל-Auth)
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">
                      תפקיד
                    </label>
                    <select
                      value={selectedUser.Role}
                      onChange={(e) => setSelectedUser({ ...selectedUser, Role: e.target.value as any })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="user">👤 משתמש</option>
                      <option value="coach">👨‍🏫 מאמן</option>
                      <option value="admin">👑 מנהל</option>
                    </select>
                  </div>

                  <div className="flex gap-3 pt-4">
                    <button
                      type="button"
                      onClick={() => setShowEditModal(false)}
                      className="flex-1 px-4 py-3 border-2 border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
                    >
                      ביטול
                    </button>
                    <button
                      type="submit"
                      className="flex-1 px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                    >
                      💾 שמור שינויים
                    </button>
                  </div>
                </form>
              </motion.div>
            </div>
          </>
        )}
      </AnimatePresence>
    </div>
  )
}